//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mylist.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mylistEntities : DbContext
    {
        public mylistEntities()
            : base("name=mylistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<list> list { get; set; }
        public DbSet<list_type> list_type { get; set; }
        public DbSet<log_type> log_type { get; set; }
        public DbSet<logs> logs { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<user_group> user_group { get; set; }
        public DbSet<user_list> user_list { get; set; }
        public DbSet<user_list_status> user_list_status { get; set; }
    }
}
