//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mylist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class list
    {
        public list()
        {
            this.user_list = new HashSet<user_list>();
        }
    
        public int list_id { get; set; }
        public string name { get; set; }
        public Nullable<int> episode { get; set; }
        public int list_type_id { get; set; }
        public bool aktif { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
    
        public virtual list_type list_type { get; set; }
        public virtual ICollection<user_list> user_list { get; set; }
    }
}
