//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mylist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_list_status
    {
        public user_list_status()
        {
            this.user_list = new HashSet<user_list>();
        }
    
        public int user_list_status_id { get; set; }
        public string status_name { get; set; }
        public Nullable<int> list_type_id { get; set; }
    
        public virtual list_type list_type { get; set; }
        public virtual ICollection<user_list> user_list { get; set; }
    }
}
