//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mylist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.user_list = new HashSet<user_list>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> age { get; set; }
        public string email { get; set; }
        public bool aktif { get; set; }
        public Nullable<System.DateTime> registerdate { get; set; }
        public int user_group_id { get; set; }
    
        public virtual user_group user_group { get; set; }
        public virtual ICollection<user_list> user_list { get; set; }
    }
}
